# Discount Reward

In [3]:
from scipy.signal import lfilter
import numpy as np

In [4]:
def discount(x, gamma):
    return lfilter([1], [1, -gamma], x[::-1], axis=0)[::-1]

In [5]:
x = [0.1, 0.2, 0.3, 0.4]

In [6]:
discount(x, 1)

array([ 1. ,  0.9,  0.7,  0.4])

In [7]:
 def discount_reward(x, gamma=1):
        buffer_x = np.zeros_like(x)
        running_r = 0
        for i in reversed(range(len(x))):
            running_r += x[i]
            buffer_x[i] = running_r
            print (running_r)
        return buffer_x

In [8]:
discount_reward(x)

0.4
0.7
0.8999999999999999
0.9999999999999999


array([ 1. ,  0.9,  0.7,  0.4])

In [9]:
 def discount_reward(v_, x, gamma=0.8):
        buffer_x = np.zeros_like(x)
        for i in reversed(range(len(x))):
            v_ = x[i] + v_*gamma
            buffer_x[i] = v_
            print('v_:', v_)
        return buffer_x

In [10]:
buffer_r = [1, 2, 3]

In [11]:
print(discount_reward(10, buffer_r))

v_: 11.0
v_: 10.8
v_: 9.64
[ 9 10 11]


In [12]:
def discount_reward(buffer_r, v_s_, GAMMA):
    buffer_v_target = []
    for r in buffer_r[::-1]:    # reverse buffer r
        v_s_ = r + GAMMA * v_s_
        buffer_v_target.append(v_s_)
    buffer_v_target.reverse()
    return buffer_v_target

In [13]:
print(discount_reward([1, 5, 10], 10, 0.9))

[20.89, 22.1, 19.0]
