# Squeeze

In [1]:
import tensorflow as tf
import numpy as np

/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
sess = tf.InteractiveSession()

In [3]:
arr = np.array([[1]])

In [4]:
print (arr.shape)

(1, 1)


In [5]:
arr2 = tf.convert_to_tensor(arr)

In [6]:
arr2= tf.squeeze(arr2)

In [7]:
print(arr2.eval())

1


In [8]:
print(arr2.get_shape())

()


In [9]:
arrx = np.array([[1,2, 3], [2, 3, 4], [4, 5,6], [6, 7,8]])

In [10]:
print (arrx.shape)

(4, 3)


In [11]:
arrxt = tf.convert_to_tensor(arrx)

In [12]:
print (arrxt.eval())

[[1 2 3]
 [2 3 4]
 [4 5 6]
 [6 7 8]]


In [13]:
print (arrxt.get_shape())

(4, 3)


In [14]:
arr = np.array([[1], [2]])

In [15]:
print (arr.shape)

(2, 1)


In [16]:
arr2 = tf.convert_to_tensor(arr)

In [17]:
arr2 = tf.squeeze(arr2)

In [18]:
print (arr2.eval())

[1 2]


In [19]:
print (arr2.get_shape())

(2,)
